spring:
  datasource:
    url: jdbc:mysql://124.71.109.112:3306/ztll?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=true&enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  ip: 124.71.109.112
  port: 9000
mybatis:
  mapper-locations: classpath:mapper/*.xml  # 扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: /home/files/
    #    path: D:/CodeFile/java/SpringBoot/springboot+vue/files/
